### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by giovannicoppola** [wsargent/toodledo#9]
Hi, I also have an issue with the setup command, pasted below. 
thanks!
giovanni

$ toodledo setup
/Library/Ruby/Gems/2.0.0/gems/cmdparse-3.0.0/lib/cmdparse.rb:773:in `initialize': wrong number of arguments (2 for 0) (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/toodledo-1.4.1/lib/toodledo/command_line/client.rb:884:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/toodledo-1.4.1/lib/toodledo/command_line/client.rb:884:in `main'
	from /Library/Ruby/Gems/2.0.0/gems/toodledo-1.4.1/bin/toodledo:11:in `<top (required)>'
	from /usr/bin/toodledo:23:in `load'
	from /usr/bin/toodledo:23:in `<main>'

**Comment by studgeek** [comment]
I am seeing this also. I see the same error when I try and run anything.

**Comment by jamespo** [comment]
This can be fixed by specifically installing v2.0.5 of cmdparse

**Comment by giovannicoppola** [comment]
thanks!

**Comment by wsargent** [comment]
@jamespo can you submit a PR for this issue?

**Comment by wsargent** [comment]
Fixed in 1.4.2
